# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngaraapp', '0002_auto_20171114_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='service',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='contact',
            name='Location',
            field=models.CharField(default='location', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='contact',
            name='estate',
            field=models.CharField(default='estate', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='firstName',
            field=models.CharField(default='firstname', max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='lastName',
            field=models.CharField(default='lastname', max_length=30),
        ),
        migrations.AlterField(
            model_name='about',
            name='service',
            field=models.CharField(default='general', max_length=30),
        ),
    ]
